# TODO: Also create a GitOpsCluster.apps.open-cluster-management.io
{{- range .Values.site.managedSites }}
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: {{ .name }}-site-policy
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: {{ .name }}-site-config
        spec:
          remediationAction: enforce
          severity: med
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: argoproj.io/v1alpha1
                kind: Application
                metadata:
                  name: {{ $.Values.site.name }}-site
                  namespace: openshift-gitops
                  finalizers:
                  - argoproj.io/finalizer
                spec:
                  project: default
                  source:
                    repoURL: {{ coalesce .repoURL $.Values.global.repoURL }}
                    targetRevision: {{ coalesce .targetRevision $.Values.global.targetRevision }}
                    path: {{ .path }}
                    helm:
                      valueFiles:
                      - "{{ coalesce .valuesDirectoryURL $.Values.global.valuesDirectoryURL }}/values-global.yaml"
                      - "{{ coalesce .valuesDirectoryURL $.Values.global.valuesDirectoryURL }}/values-{{ $.Values.site.name }}.yaml"
                      parameters:
                      - name: global.repoURL
                        value: $ARGOCD_APP_SOURCE_REPO_URL
                      - name: global.targetRevision
                        value: $ARGOCD_APP_SOURCE_TARGET_REVISION
                      - name: global.valuesDirectoryURL
                        value: {{ coalesce .valuesDirectoryURL $.Values.global.valuesDirectoryURL }}
                     {{- range .helmOverrides }}
                      - name: {{ .name }}
                        value: {{ .value }}
                     {{- end }}
                  destination:
                    server: https://kubernetes.default.svc
                    namespace: openshift-gitops
                  syncPolicy:
                    automated:
                      prune: false
                      selfHeal: true
                  ignoreDifferences:
                  - group: apps
                    kind: Deployment
                    jsonPointers:
                    - /spec/replicas
                  - group: route.openshift.io
                    kind: Route
                    jsonPointers:
                    - /status
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: {{ .name }}-placement-binding
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
placementRef:
  name: {{ .name }}-placement
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: {{ .name }}-site-policy
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: {{ .name }}-placement
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector: {{ .clusterSelector | toPrettyJson }}
---
{{- end }}
