apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: apply-argocd-to-ready-clusters
  namespace: openshift-gitops
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
